import { ItemType } from './types';

const albums: Array<ItemType> = [
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'albums',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'playlists',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'artists',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'albums',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'playlists',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'artists',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'albums',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'playlists',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'artists',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'albums',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'playlists',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'artists',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'albums',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'playlists',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'artists',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'albums',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'playlists',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'artists',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'albums',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'playlists',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'artists',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'albums',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'playlists',
  },
  {
    author: 'Miyagi & Endspiel',
    title: 'NARRATIVE',
    subTitle: '',
    image: 'https://i1.sndcdn.com/artworks-Tm4yZyaauAoN1v0u-UowOOw-t500x500.jpg',
    type: 'artists',
  },
];
const playlists: Array<ItemType> = [];
const artists: Array<ItemType> = [];

export const items: Array<ItemType> = [...albums, ...playlists, ...artists];

export const menuConfig = {
  default: 420,
  minWidth: 78,
  maxWidth: 590,
  collapse: 280,
  expand: 590,
};
